# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stax < Formula
  desc "Powerful CLI tool for WordPress development workflows (single site and multisite)"
  homepage "https://github.com/firecrown-media/stax"
  version "2.3.0"
  license "MIT"

  depends_on "ddev" => :optional
  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firecrown-media/stax/releases/download/v2.3.0/stax_2.3.0_Darwin_x86_64.tar.gz"
      sha256 "1f784d38e9e5cbc61999c83810542bc22e0a4ce36ffcb97f7efb7dd44a324d20"

      def install
        bin.install "stax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firecrown-media/stax/releases/download/v2.3.0/stax_2.3.0_Darwin_arm64.tar.gz"
      sha256 "e53c260ec3d1e1a7dbdf6256cb3df8686c15d9bea0cb6cecee584e8eb9c7580c"

      def install
        bin.install "stax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firecrown-media/stax/releases/download/v2.3.0/stax_2.3.0_Linux_x86_64.tar.gz"
      sha256 "d9ce29d16a17ccbdf3cf75ec5ebf805363d5bc26497487727a25438d1146b8e8"
      def install
        bin.install "stax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firecrown-media/stax/releases/download/v2.3.0/stax_2.3.0_Linux_arm64.tar.gz"
      sha256 "7566041139fdcb1ca43d67a6b5a34d39c032629787a74022cd72b9108d54757a"
      def install
        bin.install "stax"
      end
    end
  end

  test do
    system "#{bin}/stax", "--version"
  end
end
