# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stax < Formula
  desc "Powerful CLI tool for WordPress multisite development workflows"
  homepage "https://github.com/firecrown-media/stax"
  version "0.4.1"
  license "MIT"

  depends_on "ddev" => :optional
  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/firecrown-media/stax/releases/download/v0.4.1/stax_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "7ff26a926660d3b9620241d28a174ed98246e1e67b11ab61d41f4deb8f7f6590"

      def install
        bin.install "stax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/firecrown-media/stax/releases/download/v0.4.1/stax_0.4.1_Darwin_arm64.tar.gz"
      sha256 "98c21a3f35dd7cdd9345a91fc081ccc0d4ff9e160b311a7a33b0da89d2ec6174"

      def install
        bin.install "stax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/firecrown-media/stax/releases/download/v0.4.1/stax_0.4.1_Linux_x86_64.tar.gz"
      sha256 "a4b3e49f6b8fbf60e4562e065441f4c57d340423232f32dd4cfd63bf3d5c17ca"
      def install
        bin.install "stax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/firecrown-media/stax/releases/download/v0.4.1/stax_0.4.1_Linux_arm64.tar.gz"
      sha256 "fdd0b79fd6b001e4754e4e066a0b27a8432fe211ab6b32a0532e56c88268a86a"
      def install
        bin.install "stax"
      end
    end
  end

  test do
    system "#{bin}/stax", "--version"
  end
end
